### ISSUE TITLE
Develop an initial functional version of compare.file.directories

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/compare.file.directories#1]
# Overview

We were sometimes losing files while transitioning them between OneDrive and SharePoint. Manually trying to figure out which files are being lost is tedious, time-consuming, and error-prone. This package is intended to make it relatively quick and easy to:

1. Figure out if any files were lost when copying `directory D` from `location A` to `location B`.
2. If so, which files were lost.
3. Move the missing files from `location A` to `location B` - making it complete.

**NOTE:** If you _move_ (i.e., drag or cut and paste) `directory D` from `location A` to `location B`, then `directory D` will no longer exist in `location A`. If `directory D` doesn't exist in `location A`, then there are no files in `location A` to use as a comparison for `location B`. Therefore, _copy_ `directory D` from `location A` to `location B`. You can always delete `directory D` from `location A` _after_ you are satisfied that all files were copied over successfully.

## CRAN

At this point, I have **NO** intention of sending this package to CRAN. It is intended for internal use only. So, do make it well, but don't worry about making it usable to everyone else in the world.

# Left off at

2023-08-01: Working through the initial design in a vignette titled `Developing Compare File Directories`. 
- I have all the basic functionality built. 
- The output message could be prettier, but that isn't a top priority.
- I was running short on time and needed to compare the L2C data backup, so I didn't finish putting the code into function form. Pick back up on line 646: Make package functions.

# Tasks

- [ ] Finish `Developing Compare File Directories` vignette
- [ ] Move functions over to R scrips
- [ ] Create an add-in
- [ ] Write some _very_ basic unit tests
- [ ] Add package down
